Update pipeset

diff --git a/pipeset b/pipeset
--- a/pipeset
+++ b/pipeset
@@ -6,8 +6,7 @@ YELLOW="\e[33m"
 ENDCOLOR="\e[0m"
 
 help () {
-    echo "Pipeset - Override pipewire running configuration by setting forced values"
-    echo -e "\n${BLUE}[+]${ENDCOLOR} Usage: pipeset [Option]\n"
+    echo -e "Usage: pipeset [Option]\n"
     echo "Options:"
 
     echo -e "\t-s"
@@ -23,7 +22,6 @@ help () {
 
     echo -e "\t-d"
     echo -e "\t\tRemoves the overriden values and lets pipewire handle the sample rate and buffer size"
-    exit 1
 }
 
 print_status () {
@@ -37,28 +35,28 @@ set_defaults() {
     current2=$(pw-metadata -n settings | grep clock.force.rate | cut -d ':' -f 5 | tr -d "'" | cut -d ' ' -f 1)
 
     if [[ "$current1" -eq 0 && "$current2" -eq 0 ]]; then
-        echo -e "\n${YELLOW}[#]${ENDCOLOR} Defaults already set"
+        echo -e "\n${YELLOW}[!]${ENDCOLOR} Defaults already set"
         exit 2
     fi
 
-    echo -e "\n${BLUE}[+]${ENDCOLOR} Overridden values removed"
     pw-metadata -n settings 0 clock.force-quantum 0 >/dev/null
     pw-metadata -n settings 0 clock.force-rate 0 >/dev/null
+    echo -e "\n${BLUE}[+]${ENDCOLOR} Overridden values removed"
 }
 
 set_size () {
     current=$(pw-metadata -n settings | grep clock.force.quantum | cut -d ':' -f 5 | tr -d "'" | cut -d ' ' -f 1)
 
     if [[ "$current" == "$1" ]]; then
-        echo -e "\n${YELLOW}[#]${ENDCOLOR} Buffer size already set to that vaule"
+        echo -e "\n${YELLOW}[!]${ENDCOLOR} Buffer size already set to that vaule"
         exit 2
     fi
 
     if [[ "$1" -eq 64 || "$1" -eq 128 || "$1" -eq 256 || "$1" -eq 512 || "$1" -eq 1024 ]]; then
-        echo -e "\n${BLUE}[+]${ENDCOLOR} Buffer size set to: ${YELLOW}$1${ENDCOLOR}"
         pw-metadata -n settings 0 clock.force-quantum $1 >/dev/null
+        echo -e "\n${BLUE}[+]${ENDCOLOR} Buffer size set to: ${YELLOW}$1${ENDCOLOR}"
     else
-        echo -e "\n${RED}[!]${ENDCOLOR} Invalid argument."
+        echo -e "\n${RED}[x]${ENDCOLOR} Invalid argument."
         echo -e "\nAvailable options: [64, 128, 256, 512, 1024]"
         exit 1
     fi
@@ -73,10 +71,10 @@ set_rate () {
     fi
 
     if [[ "$1" -eq 44100 || "$1" -eq 48000 || "$1" -eq 96000 || "$1" -eq 192000 ]]; then
-        echo -e "\n${BLUE}[+]${ENDCOLOR} Sample rate set to: ${YELLOW}$1${ENDCOLOR}"
         pw-metadata -n settings 0 clock.force-rate $1 >/dev/null
+        echo -e "\n${BLUE}[+]${ENDCOLOR} Sample rate set to: ${YELLOW}$1${ENDCOLOR}"
     else
-        echo -e "\n${RED}[!]${ENDCOLOR} Invalid argument."
+        echo -e "\n${RED}[x]${ENDCOLOR} Invalid argument."
         echo -e "\nAvailable options: [44100, 48000, 96000, 192000]"
         exit 1
     fi
@@ -87,8 +85,13 @@ option_b=0
 option_r=0
 option_d=0
 
-while getopts ":sb:r:d" option; do
+while getopts ":sb:r:dh" option; do
     case $option in
+        h)
+            echo "Pipeset - Override pipewire running configuration by setting forced values"
+            help
+            exit 0
+            ;;
         s)
             option_s=1
             ;;
@@ -104,23 +107,25 @@ while getopts ":sb:r:d" option; do
             option_d=1
             ;;
         \?)
-            echo -e "\n${RED}[!]${ENDCOLOR} Invalid option"
+            echo -e "\n${RED}[x]${ENDCOLOR} Invalid option\n"
             help
             exit 1
             ;;
         :)
-            echo -e "\n${RED}[!]${ENDCOLOR} Option${YELLOW} -$OPTARG${ENDCOLOR} requires an argument" 1>&2
+            echo -e "\n${RED}[x]${ENDCOLOR} Option${YELLOW} -$OPTARG${ENDCOLOR} requires an argument" 1>&2
             exit 1
             ;;
     esac
 done
 
 if [[ "$((option_s + option_b + option_r + option_d))" -eq 0 ]]; then
+    echo -e "\n${RED}[x]${ENDCOLOR} Must select an option"
     help
+    exit 1
 fi
 
 if [[ "$((option_s + option_b + option_r + option_d))" -ne 1 ]]; then
-    echo -e "\n${RED}[!]${ENDCOLOR} Select only one option"
+    echo -e "\n${RED}[x]${ENDCOLOR} Select only one option"
     exit 1
 fi
 
